### ISSUE TITLE
Custom Data source Viewer not rendering - black blank screen

### ISSUE THREAD

**Issue by highoncarbs** [OHIF/Viewers#4161]
### Describe the Bug

I wanted the viewer to be accessible like this `/vewier/scan?id=6sdasd838878sad` 

So I created a new datasource in `/extensions/default/src/ScanIdDataSource/index.js` , which is basically a clone of DicomJSONDataSource updated to fetch the id param and query an API, this returns dicomJSON. 

When I go to this route, the console prints the statements `ScanIdDataSource/index.js`, but nothing renders on the screen and no console errors.  

### Steps to Reproduce

This is the script  `/extensions/default/src/ScanIdDataSource/index.js`  that is printing the console logs
![image](https://github.com/OHIF/Viewers/assets/6228854/e006e29b-176b-4795-958f-05fd0d6f1fa6)

Added to datasources
![image](https://github.com/OHIF/Viewers/assets/6228854/c9c0cd81-b849-45b6-b231-beef525856b0)

Browser View 
![image](https://github.com/OHIF/Viewers/assets/6228854/b0ea5e15-b7e0-4f81-92a3-a1c0d34bf64b)

Console 
![image](https://github.com/OHIF/Viewers/assets/6228854/b7ea5c58-e915-4de2-a507-f6d000b3cf52)

### The current behavior

Blank Viewer

### The expected behavior

It should load the scans in the Viewer

### OS

Windows 11

### Node version

20

### Browser

Latest Chrome and edge

**Comment by highoncarbs** [comment]
Alright , I think this issue is with v3.9, it's working on v3.5

**Comment by highoncarbs** [comment]
Ok, so I made it to route correctly on 3.8, but it is throwing an error on my customDatasource

`TypeError: dataSource.getStudyInstanceUIDs is not a function`

And the same data works in dicomJSON @sedghi , would love to get your quick help on this

**Comment by sedghi** [comment]
can you implement getStudyInstanceUIDs maybe?
