### ISSUE TITLE
Latest source can not get/display image

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#102]
I tried latest source but it don't work.

When double-click patient in study list, Loading...showed and get error 

Web log console:
MetadataProvider.js:346 GET http://localhost:3000/__wado_proxy?url=http%3A%2F%2F192.168.201.60%3A1000%2…761.19284%26contentType%3Dapplication%252Fdicom&serverId=GsPSKjvr3oaMzxmGy 500 (Internal Server Error)

Server log:
I20170817-11:10:54.246(7)? /__wado_proxy?url=http%3A%2F%2F192.168.201.60%3A1000%2Fwado%2FCT%3FrequestType%3DWADO%26studyUID%3D1.2.392.200036.9123.100.11.15000165473693810149577533800352752%26**seriesUID%3D**%26objectUID%3D2.16.840.1.113669.632.21.1762331146.20170526.360488732.761.19284%26contentType%3Dapplication%252Fdicom&serverId=GsPSKjvr3oaMzxmGy: 2023ms

I checked and found out seriesUID value in the url is empty (seriesUID%3D).

It worked well for me with old source
Correct url log:
I20170817-11:15:16.796(7)? /__wado_proxy?url=http%3A%2F%2F192.168.201.60%3A1000%2Fwado%2FCT%3FrequestType%3DWADO%26studyUID%3D1.2.392.200036.9123.100.11.15000165473693810149577533800352752%26**seriesUID%3D2.16.840.1.113669.632.21.1762331146.20170526.360487877.0.7.44241**%26objectUID%3D2.16.840.1.113669.632.21.1762331146.20170526.360487877.0.9.44241%26contentType%3Dapplication%252Fdicom&serverId=f3qQA8KZymakwp8di: 8ms

Please help me how can I fix it?
My PACS Server is connected to: CC image server

Thank you.
lam0620

**Comment by ayselafsar** [comment]
Hi @lam0620,
Are you still having this problem?

**Comment by lam0620** [comment]
Hi @ayselafsar ,

I tried to build lastest source today from master. I got error when loading first page (studylist page).
Meteor version: 1.5
Node version: 8.4.0
OS: Centos 7

I tried to build on Windows 10 (meteor: 1.4.2.3, node: 6.11.3), I got also same error.

Could you know why?

Error log:
=> Meteor server restarted
I20171009-17:40:27.595(7)? Services.DIMSE.Studies
I20171009-17:40:27.596(7)? Associating...
I20171009-17:40:27.597(7)? Starting Connection...
I20171009-17:40:27.601(7)? Connect
I20171009-17:40:27.602(7)? Connection established
I20171009-17:40:27.620(7)? ==Associated
W20171009-17:40:28.013(7)? (STDERR) /var/ohif/svn_src/Viewers/OHIFViewer/.meteor/local/build/programs/server/packages/ohif_dicom-services.js:22997
W20171009-17:40:28.014(7)? (STDERR)         var result = this.findStudies(Object.assign(defaultParams, params)),                                           // 161
W20171009-17:40:28.015(7)? (STDERR)                           ^
W20171009-17:40:28.015(7)? (STDERR)
W20171009-17:40:28.016(7)? (STDERR) TypeError: this.findStudies is not a function
W20171009-17:40:28.016(7)? (STDERR)     at packages/ohif:dicom-services/server/DIMSE/DIMSE.js:161:27
W20171009-17:40:28.017(7)? (STDERR)     at [object Object].<anonymous> (packages/ohif:dicom-services/server/DIMSE/DIMSE.js:85:9)
W20171009-17:40:28.024(7)? (STDERR)     at [object Object].g (events.js:260:16)
W20171009-17:40:28.024(7)? (STDERR)     at emitOne (events.js:77:13)
W20171009-17:40:28.025(7)? (STDERR)     at [object Object].emit (events.js:169:7)
W20171009-17:40:28.025(7)? (STDERR)     at [object Object].CSocket.interpret (packages/ohif:dicom-services/server/DIMSE/CSocket.js:347:18)
W20171009-17:40:28.026(7)? (STDERR)     at [object Object].CSocket.process (packages/ohif:dicom-services/server/DIMSE/CSocket.js:294:18)
W20171009-17:40:28.041(7)? (STDERR)     at [object Object].CSocket.received (packages/ohif:dicom-services/server/DIMSE/CSocket.js:260:21)
W20171009-17:40:28.042(7)? (STDERR)     at Socket.<anonymous> (packages/ohif:dicom-services/server/DIMSE/CSocket.js:51:11)
W20171009-17:40:28.043(7)? (STDERR)     at emitOne (events.js:77:13)

**Comment by ayselafsar** [comment]
Hi @lam0620 

The fix for the issue is on master branch, commit: 9905773a704b52950f89e50941e5e735d4dbcbf0

Could you please give it a try? Thanks.

**Comment by lam0620** [comment]
Hi @ayselafsar 

It works. Thank you so much.

But I found another issue that I got repeat same reocords in study list search result of LesionTracker when focus at Study Date and Enter.

**Comment by swederik** [comment]
Can you file that as a separate ticket then? Thanks
