### ISSUE TITLE
[Bug] Something went wrong in Route template.

### ISSUE THREAD

**Issue by Jeniamakarchik** [OHIF/Viewers#5086]
### Describe the Bug

When I am trying to open a Custom Mode that I created the "Something went wrong in Route template." error is shown. 

TypeError: props.evaluate is not a function
    at evaluateButtonProps (app.js:134234:43)
    at http://localhost:3000/app.js:134279:32
    at Array.forEach (<anonymous>)
    at http://localhost:3000/app.js:134277:23
    at Array.forEach (<anonymous>)
    at ToolbarService.refreshToolbarState (app.js:134249:28)
    at Object.callback (app.js:126591:24)
    at http://localhost:3000/app.js:136264:16
    at Array.forEach (<anonymous>)
    at ViewportGridService._broadcastEvent (app.js:136263:31)

### Steps to Reproduce

1. I downloaded .zip file for OHIF release/v3.10
2. Created a mode using video tutorial in documentation
3. I did an extra step and run "yarn install" inside mode folder as without it mode wasn't shown at all in the study menu
4. Push the button for "Testing mode" 

### The current behavior

After I have pushed the button "Testing Mode" the error appear.

![Image](https://github.com/user-attachments/assets/133f8fe2-79af-4a8e-8eac-7011a9483871)

### The expected behavior

Expect to see the default view 

### OS

Windows 10

### Node version

v22.16.0

### Browser

Brave  v1.79.118, Chromium 137.0.7151.61

**Comment by jbocce** [comment]
@Jeniamakarchik how does it behave in 3.11?

**Comment by Jeniamakarchik** [comment]
@jbocce tried it on master branch and it did work.

**Comment by jbocce** [comment]
@Jeniamakarchik considering it works in the latest version could you please consider closing this issue and you can work with 3.11? Thanks. We don't typically develop off released versions.

**Comment by Jeniamakarchik** [comment]
Thank you!
